### ISSUE TITLE
Runtime upgrade deployment strategy

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#445] opened 2020-10-23 12:53 UTC
Currently every runtime upgrade will break the relayer, cause the `spec_version` is hardcoded in the transaction generated by the relayer.

While most of the runtime upgrades should not require any changes in the relayer, it's still a manual operation to confirm that.
We could have spec_version being passed as a CLI parameter, in such case the relayers would simply need to be restarted with an updated `spec_version`, but re-compilation (or re-deployment) would not be needed.

Even with some workarounds we should make sure to come up with some strategy about runtime upgrades to ensure the bridge is operational.

We might consider having two relayers running in a "fallback" mode or sth, so that whenever the first one stops producing transactions (because of the spec_version mismatch), the second one takes over (we can pre-deploy it with the new `spec_version`).

Related #538

**Comment by EmmanuellNorbertTulbure** [comment] 2023-03-07 17:23
Duplicate of #826

**Closed by EmmanuellNorbertTulbure** 2023-03-07 17:23 UTC
Labels: A-feat, P-Relay
