### ISSUE TITLE
Rialto <> Millau alert notifications are not generated anymore

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#2035] opened 2023-04-12 13:01 UTC
after old server has been shut down?

**Comment by serban300** [comment] 2023-04-14 07:28
https://gitlab.parity.io/parity/mirrors/parity-bridges-common/-/jobs/2682960

**Comment by serban300** [comment] 2023-04-14 08:05
In the `paritytech/bridges-ci` docker image, the `wasm32-unknown-unknown` target is installed for the nightly toolchain, but not for stable. 

Trying to understand why this happened. But we should probably install it for stable as well.

**Comment by serban300** [comment] 2023-04-14 10:00
[This](https://hub.docker.com/layers/paritytech/bridges-ci/963c32e8-20230331/images/sha256-084f955c30190873bf588bba3ab20eb3478583045808cd2a9d88a442c342d581?context=explore) is the first image where the build fails. 

In the previous image we still didn't have `wasm32-unknown-unknown` installed for stable:
```
[32;1m$ rustup show[0;m
Default host: x86_64-unknown-linux-gnu
rustup home:  /usr/local/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)

[32;1m$ cargo --version[0;m
cargo 1.67.1 (8ecd4f20a 2023-01-10)
[32;1m$ rustup +nightly show[0;m
Default host: x86_64-unknown-linux-gnu
rustup home:  /usr/local/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.70.0-nightly (e3dfeeaa4 2023-03-07)
```

I don't see significant differences in the `bridges-ci` dockerfile. Maybe it's because of the new version of rustc: `1.68.2` vs `1.67.1`. Maybe the previous version of rust/cargo would use `wasm32-unknown-unknown` from nightly if it wasn't installed on stable. I don't know.

Anyway if we do `rustup target add wasm32-unknown-unknown` in the latest image, the build succeeds. Tried it locally inside docker.

**Comment by serban300** [comment] 2023-04-17 17:53
The build finally succeeded: https://gitlab.parity.io/parity/mirrors/parity-bridges-common/-/jobs/2692482

The updated images were published.

But:

1. The alerts are still not published even though the nodes and the relayers start and the nodes running alert gets activated after deploying:
```
2023-04-17 17:46:08 - SocketError - Failed to open TCP connection to matrix.parity.io:443 (getaddrinfo: Name does not resolve):
	/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
	/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	/usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	/usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	/usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	/usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	/usr/local/lib/ruby/3.0.0/net/http.rb:965:in `start'
```

3. For Rialto Parachain <-> Millau there seems to be a problem with relaying the messages

**Comment by serban300** [comment] 2023-04-18 12:11
Matrix bot request: https://github.com/paritytech/devops/issues/2507

**Comment by serban300** [comment] 2023-04-19 17:04
Configured the new bot. Everything should work. Still have to update the docs

**Comment by serban300** [comment] 2023-04-19 17:28
One more thing to investigate:

1-2h after doing a test deployment, I'm getting high CPU load, expecially from millau-node-alice and a lot of logs like this:

```
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23483, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abb5b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abb5b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23484, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abc5b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abc5b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23485, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abd5b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abd5b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23486, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abe5b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abe5b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23487, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abf5b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1abf5b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23488, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac05b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac05b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23489, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac15b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac15b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23490, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac25b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac25b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23491, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac35b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac35b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23492, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac45b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac45b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23493, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac55b0000 vs ["da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac55b0000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c4c590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c4d590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c4e590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c4f590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c50590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c51590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c52590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c53590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c54590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c55590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c56590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c57590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c58590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c59590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5a590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5b590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5c590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5d590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5e590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c5f590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c60590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c61590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c62590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c63590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c64590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c65590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c66590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c67590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c68590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c69590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6a590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6b590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6c590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6d590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6e590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c6f590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c70590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c71590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c72590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c73590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c74590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c75590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c76590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c77590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c78590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c79590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c7a590000"]    
2023-04-19 17:21:37.314 DEBUG tokio-runtime-worker rpc: Current nonce to 23494, checking da842bf0dcb206e0a8b6684ccca8b504486259dd000df83d94ee79a825ef6e1ac65b0000 vs ["98cf4d987302792080b54cdb23392216c3c5ff6ba58805c06781e3326b6ff35c7b590000"]    

```

**Comment by serban300** [comment] 2023-04-20 06:15
Also there seems to be an issue with the westend-millau headers relayer

**Comment by serban300** [comment] 2023-04-20 06:17
> Also there seems to be an issue with the westend-millau headers relayer

Probably it's not bridge related. Westend is not producing blocks

**Comment by serban300** [comment] 2023-04-20 09:39
The CPU load issue doesn't seem to reproduce anymore. Probably it was something related to my local build.

Resolving the issue.

**Closed by serban300** 2023-04-20 09:39 UTC
Labels: A-chores
