### ISSUE TITLE
Fix `tools/codegen` util

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2669] opened 2023-11-02 09:07 UTC
When I tried to regenerate codegen-runtimes: https://github.com/paritytech/parity-bridges-common/blob/polkadot-staging/scripts/regenerate_runtimes.sh#L14-L16
from `polkadot-sdk` master wasm files, there was some inconsistency with subxt with  `Header` one vs two arguments,
I didnt investigate it further, probably subxt is not adjusted to some `polkadot-sdk` stuff.

```
error[E0107]: struct takes 2 generic arguments but 1 generic argument was supplied
    --> relays/client-bridge-hub-westend/src/codegen_runtime.rs:1133:31
     |
1133 | ...                   ::sp_runtime::generic::Header<::core::primitive::u32>,
     |                                              ^^^^^^ ---------------------- supplied 1 generic argument
     |                                              |
     |                                              expected 2 generic arguments
     |
note: struct defined here, with 2 generic parameters: `Number`, `Hash`
    --> /home/bparity/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/1cf7d3a/substrate/primitives/runtime/src/generic/header.rs:41:12
     |
41   | pub struct Header<Number: Copy + Into<U256> + TryFrom<U256>, Hash: HashT> {
     |            ^^^^^^ ------                                     ----
help: add missing generic argument
     |
1133 |                             ::sp_runtime::generic::Header<::core::primitive::u32, Hash>,
```

**Comment by bkontur** [comment] 2023-11-02 09:08
@serban300 for Rococo/Westend I manualy edited `codegen-runtime.rs` to add Westend enums there, 
could you please take a look when have time?

**Comment by serban300** [comment] 2023-11-02 09:10
Yes, sure, I'll take a look. Probably today.

**Comment by serban300** [comment] 2023-11-03 12:39
It doesn't seem to be a `subxt-codegen` issue. The problem is that the metadata extracted from the wasm looks something like:

```
            type: {
              path: [
                sp_runtime
                generic
                header
                Header
              ]
              params: [
                {
                  name: Number
                  type: 4
                }
                {
                  name: Hash
                  type: None
                }
              ]
```

And before it was like this:

```
            type: {
              path: [
                sp_runtime
                generic
                header
                Header
              ]
              params: [
                {
                  name: Number
                  type: 4
                }
                {
                  name: Hash
                  type: 265
                }
              ]
```

The problem is that:
```
                {
                  name: Hash
                  type: None
                }
```

It's probably a runtime metadata issue or a wasm-loader issue. Researching

**Comment by serban300** [comment] 2023-11-03 16:20
Found what's causing the metadata change:

A [#[scale_info(skip_type_params(Hash))]](https://github.com/paritytech/polkadot-sdk/blob/cd2d5d2579f12dff6d6999b5c9e1f011dcd19a36/substrate/primitives/runtime/src/generic/header.rs#L37) has been added to the structure.

**Comment by serban300** [comment] 2023-11-06 09:14
Opened an issue in the `subxt` repo related to this: https://github.com/paritytech/subxt/issues/1247

**Comment by serban300** [comment] 2024-08-20 13:38
It was fixed by this:

```
https://github.com/paritytech/parity-bridges-common/blob/8593aef5896e96cacb4a28b42e39a0c05cd7a3b5/scripts/regenerate_runtimes.sh#L27-L29
```

Since we can't do a better fix in subxt, I will close this issue.

**Closed by serban300** 2024-08-20 13:38 UTC

**Comment by bkontur** [comment] 2024-10-01 08:00
> It was fixed by this:
> 
> ```
> https://github.com/paritytech/parity-bridges-common/blob/8593aef5896e96cacb4a28b42e39a0c05cd7a3b5/scripts/regenerate_runtimes.sh#L27-L29
> ```
> 
> Since we can't do a better fix in subxt, I will close this issue.


@serban300 what about doing this "find/seed replace" in rust code directly in tools/runtime-codegen? It could save us time when regenerating :)
