### ISSUE TITLE
Change grafana alert conditions on test deployments

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1369] opened 2022-04-05 07:26 UTC
There are still some alerts that are starting with "[No Data]" state when deployments restarts:
```
[No Data] Rewards are not being confirmed
[No Data] Messages generated at Millau are not detected by relay
[No Data] Too many unconfirmed messages
[No Data] At-Rialto relay balances are too low
```

There are imo two solutions:
1) to change alert settings to not to fire if there's no data;
2) change alert formula so that it'll not fire if data is unavailable.

**Comment by svyatonik** [comment] 2022-06-22 12:10
shall be fixed now

**Comment by serban300** [comment] 2022-08-23 11:24
I've been experimenting with this. I think we could set
`If no data or all values are null - set state to - keep last state`
for all these alerts. 

And I'm trying to see if we can add a metric + alert on uptime in order to receive a notification when the deployments are restarted.

**Comment by serban300** [comment] 2022-08-24 08:29
A couple of updates:

- I managed to create an alarm on nodes uptime which would trigger on each restart. This seems reliable
- I tried to set `"noDataState": "keep_state"` for all the current alerts. It doesn't seem to generate any issues. The problem is that if we do this, in case we have a problem with a metric and it doesn't log anymore, we won't get any notification. So it doesn;t seem very safe.
- It would be nice if we could delay the alerts evaluation on no data somehow, but I couldn't find any way to do this in a generic way for all the alerts. Still researching.

**Comment by serban300** [comment] 2022-08-24 12:11
Options so far:

1. Setting `"noDataState": "keep_state"` for all the alerts. But if we do this, in case we have a problem with a metric and it doesn't log anymore, we won't get any notification. So it doesn't seem safe.
2. Changing the queries or adding another query which has a default value which would trigger the alarm. For example for the `Rewards are not being confirmed (Millau -> RialtoParachain messages)` alarm, we have the following query:
```
  (
      scalar(
          max_over_time(
            Millau_to_RialtoParachain_MessageLane_00000000_lane_state_nonces{instance="relay-millau-rialto-parachain-1:9616",type="source_latest_confirmed"}[2m]
          )
        or on ()
          vector(0)
      )
    -
      scalar(
          max_over_time(
            Millau_to_RialtoParachain_MessageLane_00000000_lane_state_nonces{instance="relay-millau-rialto-parachain-1:9616",type="target_latest_confirmed"}[2m]
          )
        or on ()
          vector(0)
      )
  )
*
  (
      max_over_time(
        Millau_to_RialtoParachain_MessageLane_00000000_lane_state_nonces{instance="relay-millau-rialto-parachain-1:9616",type="target_latest_received"}[2m]
      )
    > bool
      min_over_time(
        Millau_to_RialtoParachain_MessageLane_00000000_lane_state_nonces{instance="relay-millau-rialto-parachain-1:9616",type="target_latest_received"}[2m]
      )
  )
```
and the alarm condition is `query_result > 10`

We could add `or on() vector(11)` to the query, which would put the monitor in pending state instead of `[no_data]` at the beginning and if there is no data for a long time it will trigger the alarm. 

3. I think we could try to delay the startup of the grafana docker container with 5 minutes to make sure that there is data. Not sure how, but I suppose it should be possible.

All these options seem hacky to me, I don't see a clear winner and if I had to chose between them, I would prefer to keep the `[No Data]` warnings. Still thinking.

**Comment by serban300** [comment] 2022-08-29 07:21
Keeping this open for a while to make sure the solution works as expected

**Comment by serban300** [comment] 2022-08-29 11:40
Seems to work as expected. Closing.

**Comment by serban300** [comment] 2022-09-01 07:51
We're still getting 1 [No Data] message sometimes. We need to adjust the grafana delay. I'll try to do this when I have some spare time.

**Closed** 2022-09-05 06:29 UTC
Labels: Good First Issue, A-chores
